resolver: lts-8.13
packages:
  - '.'
  - location:
      git: https://github.com/agrafix/simple-logger
      commit: 9b359de3073bab6d3e0097cf87929a00d55b54e6
    extra-dep: true
extra-deps:
  - superrecord-0.3.0.0
