resolver: lts-9.0
packages:
  - '.'
  - location:
      git: https://github.com/agrafix/hasql-simple
      commit: b3334720595c1f425361832abad5f119570c1558
    extra-dep: true
  - location:
      git: https://github.com/agrafix/simple-logger
      commit: 9b359de3073bab6d3e0097cf87929a00d55b54e6
    extra-dep: true
extra-deps:
  - superrecord-0.3.0.0
  - megaparsec-6.1.1
  - parser-combinators-0.2.0
  - path-0.6.1
  - path-io-1.3.3
