version: 2
jobs:
  build:
    working_directory: ~/grabcite
    docker:
      - image: fpco/stack-build:lts-9.0
        environment:
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: root
    steps:
      - checkout
      - run:
          name: install apt-get dependencies
          command: 'apt-get update && apt-get install -y curl poppler-utils'
      - restore_cache:
          key: stack-cache
      - run:
          name: stack setup
          command: 'stack setup'
      - run:
          name: stack install dependencies
          command: 'stack build --test --only-dependencies'
      - save_cache:
          key: stack-cache
          paths:
            - ~/.stack
            - ~/grabcite/.stack-work
      - run:
          name: stack build
          command: 'stack build --fast --pedantic'
      - run:
          name: stack test
          command: 'stack test --fast'
