version: 2
jobs:
  build:
    working_directory: ~/grabcite
    docker:
      - image: fpco/stack-build:lts-8.13
    steps:
      - checkout
      - restore_cache:
          key: stack-cache
      - run:
          name: stack setup
          command: 'stack setup'
      - run:
          name: stack install dependencies
          command: 'stack build --test --only-dependencies'
      - save_cache:
          key: stack-cache
          paths:
            - ~/.stack
            - ~/grabcite/.stack-work
      - run:
          name: install pdftotext
          command: 'apt-get install update && apt-get install -y poppler-utils'
      - run:
          name: stack build
          command: 'stack build --fast --pedantic'
      - run:
          name: stack test
          command: 'stack test --fast'
