version: 2
jobs:
  build:
    working_directory: ~/grabcite
    docker:
      - image: ubuntu:17.10
    steps:
      - checkout
      - run:
          name: install apt-get dependencies
          command: 'apt-get update && apt-get install -y curl poppler-utils'
      - run:
          name: install stack
          command: 'curl -sSL https://get.haskellstack.org/ | sh'
      - restore_cache:
          key: stack-cache
      - run:
          name: stack setup
          command: 'stack setup'
      - run:
          name: stack install dependencies
          command: 'stack build --test --only-dependencies'
      - save_cache:
          key: stack-cache
          paths:
            - ~/.stack
            - ~/grabcite/.stack-work
      - run:
          name: stack build
          command: 'stack build --fast --pedantic'
      - run:
          name: stack test
          command: 'stack test --fast'
